AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{cookiecutter.service_name}}

  {{cookiecutter.service_description}}

Parameters:
  LogLevel:
    Type: String
    Description: "Log level for functions; used internally in code."
    Default: 'INFO'
    AllowedValues:
      - 'DEBUG'
      - 'INFO'
      - 'WARNING'
      - 'ERROR'
      - 'CRITICAL'

{% if cookiecutter.event_source != "other" %}
{%- elif cookiecutter.event_source == "cloudwatch-logs" %}
  EventCloudwatchLogGroupName:
    Type: String
    Description: "Name of triggering log group"
    #Default: <<LOGGROUP_NAME>>

  # NOTE: A filterPattern is optional
  #EventCloudwatchLogGroupFilterPattern:
  #  Type: String
  #  Default: <<FILTER_PATTERN>>
{%- elif cookiecutter.event_source == "dynamodb" %}
  EventDynamoDBStreamArn:
    Type: String
    Description: "ARN of stream"
    #Default: <<required: STREAM_ARN>>

  EventDynamoDBStreamStartingPosition:
    Type: String
    Description: "Stream starting position for function"
    AllowedValues:
      - 'LATEST'
      - 'TRIM_HORIZON'
    Default: 'LATEST'

  EventDynamoDBStreamBatchSize:
    Type: String
    Description: "Size of event batch"
    Default: 100

  # FIXME: Need a Condition block for this.
  EventDynamoDBStreamEnabled:
    Type: String
    Description: "If processing is enabled"
    AllowedValues:
      - True
      - False
    Default: True

{%- elif cookiecutter.event_source == "kinesis" %}
  EventKinesisStreamArn:
    Type: String
    Description: "ARN of stream"
    #Default: <<required: STREAM_ARN>>

  EventKinesisStreamStartingPosition:
    Type: String
    Description: "Stream starting position for function"
    AllowedValues:
      - 'LATEST'
      - 'TRIM_HORIZON'
    Default: 'LATEST'

  EventKinesisStreamBatchSize:
    Type: String
    Description: "Size of event batch"
    Default: 100

  # FIXME: Need a Condition block for this.
  EventKinesisStreamEnabled:
    Type: String
    Description: "If processing is enabled"
    AllowedValues:
      - True
      - False
    Default: True

{%- elif cookiecutter.event_source == "s3" %}
  EventS3Bucket:
    Type: String
    Description: "S3 bucket name"
    #Default: <<required: BUCKET_NAME>>

  EventS3EventsList:
    Type: List
    Description: "List of events to trigger on"
    AllowedValues:
      - s3:ObjectCreated:*
      - s3:ObjectCreated:Put
      - s3:ObjectCreated:Post
      - s3:ObjectCreated:Copy
      - s3:ObjectCreated:CompleteMultipartUpload
      - s3:ObjectRemoved:*
      - s3:ObjectRemoved:Delete
      - s3:ObjectRemoved:DeleteMarkerCreated
      - s3:ObjectRestore:Post
      - s3:ObjectRestore:Completed
      - s3:ReducedRedundancyLostObject
    #Default:
    #  - <<required: EVENT>>

  #EventS3FilterRuleList:
  #  Type: List
  #  Description: "List of event filter rules."
  #  Default:
  #    - <<FILTER_RULE>>
{%- elif cookiecutter.event_source == "schedule" %}
  EventSchedule:
    Type: String
    Description: "event schedule"
    #Default: <<required: SCHEDULE>>
{%- elif cookiecutter.event_source == "sns" %}
  EventSnsTopicArn:
    Type: String
    Description: "SNS Topic Arn"
    #Default: <<required: SNS_TOPIC_ARN>>

{%- elif cookiecutter.event_source == "sqs" %}
  EventSqsQueueArn:
    Type: String
    Description: "ARN of stream"
    #Default: <<required: STREAM_ARN>>

  EventSqsQueueBatchSize:
    Type: String
    Description: "Size of event batch"
    Default: 10

  # FIXME: Need a Condition block for this.
  EventSqsQueueEnabled:
    Type: String
    Description: "If processing is enabled"
    AllowedValues:
      - True
      - False
    Default: True

{%- endif %}
{%- endif %}


Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        LOG_LEVEL:
          Ref: LogLevel
{%- if cookiecutter.enable_xray == "y" %}
    Tracing: Active
{%- endif %}


Resources:
  {{cookiecutter.function_name}}:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/{{cookiecutter.function_name}}
      Handler: function.handler
      Runtime: python3.7
{%- if cookiecutter.event_source != "other" %}
      Events:
{%- if cookiecutter.event_source == "apigateway" %}
        Apig:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestApi
            #Path: <<required: PATH>>
            #Method: <<required: METHOD>>
{%- elif cookiecutter.event_source == "cloudwatch-event" %}
        CloudWatchEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern: <<PATTERN_OBJECT>>
{%- elif cookiecutter.event_source == "cloudwatch-logs" %}
        CloudWatchLogs:
          Type: CloudWatchLogs
          Properties:
            LogGroupName:
              Ref: EventCloudwatchLogGroupName
            #FilterPattern:
            #  Ref: EventCloudwatchLogGroupFilterPattern
{%- elif cookiecutter.event_source == "dynamodb" %}
        DynamoDB:
          Type: DynamoDB
          Properties:
            Stream:
              Ref: EventDynamoDBStreamArn
            StartingPosition:
              Ref: EventDynamoDBStreamStartingPosition
            BatchSize:
              Ref: EventDynamoDBStreamBatchSize
            Enabled:
              Ref: EventDynamoDBStreamEnabled
{%- elif cookiecutter.event_source == "kinesis" %}
        Kinesis:
          Type: Kinesis
          Properties:
            Stream:
              Ref: EventKinesisStreamArn
            StartingPosition:
              Ref: EventKinesisStreamStartingPosition
            BatchSize:
              Ref: EventKinesisStreamBatchSize
            Enabled:
              Ref: EventKinesisStreamEnabled
{%- elif cookiecutter.event_source == "s3" %}
        S3:
          Type: S3
          Properties:
            Bucket:
              Ref: EventS3Bucket
            Events:
              Ref: EventS3EventsList
            #Filter:
            #  S3Key:
            #    Ref: EventS3FilterRuleList
{%- elif cookiecutter.event_source == "schedule" %}
        Schedule:
          Type: Schedule
          Properties:
            Schedule:
              Ref: EventSchedule
{%- elif cookiecutter.event_source == "sns" %}
        SNS:
          Type: SNS
          Properties:
            Topic:
              Ref: EventSnsTopicArn
            #FilterPolicy:
            #  <<FILTER_POLICY>>
{%- elif cookiecutter.event_source == "sqs" %}
        SQS:
          Type: SQS
          Properties:
            Queue:
              Ref: EventSqsQueueArn
            BatchSize:
              Ref: EventSqsQueueBatchSize
            Enabled:
              Ref: EventSqsQueueEnabled
{%- endif %}
{%- endif %}

{% if cookiecutter.event_source == "apigateway" %}
    RestApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: 'live'
        #DefinitionUri: swagger.yml
{%- endif %}

  {{cookiecutter.function_name}}Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "root"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "ssm:GetParameters"
            Resource: "*"
      Roles:
        # This role is created implicitly by SAM.
        - Ref: {{cookiecutter.function_name}}Role


Outputs:
{%- if cookiecutter.event_source == "apigateway" %}
  # FIXME: Fix API root
  RestApiRoot:
    Description: "API Gateway endpoint URL for function"
    Value:
      Fn::Sub: "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
{%- endif %}

  {{cookiecutter.function_name}}Arn:
    Description: "Hello World Lambda Function ARN"
    Value:
      Fn::GetAtt: {{cookiecutter.function_name}}.Arn

