AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: {{cookiecutter.service_description}}

Parameters:
  ServiceName:
    Type: String
    Description: "Name of service"
    Default: "{{cookiecutter.service_name}}"

  ServiceEnv:
    Type: String
    Description: "Name of deployment environment"
    Default: "prime"

  LogLevel:
    Type: String
    Description: "Log level for functions; used internally in code."
    Default: 'INFO'
    AllowedValues:
      - 'DEBUG'
      - 'INFO'
      - 'WARNING'
      - 'ERROR'
      - 'CRITICAL'

  XRaySDKEnabled:
    Type: String
    Description: "AWS X-RAY SDK enabled"
    Default: 'Disabled'
    AllowedValues:
      - 'Enabled'
      - 'Disabled'

  XRayTracingMode:
    Type: String
    Description: "AWS XRay tracing mode"
    Default: PassThrough
    AllowedValues:
      - Active
      - PassThrough

{%- if cookiecutter.event_source != "other" %}

## Event source configuration
{%- if cookiecutter.event_source == "cloudwatch-logs" %}
  EventCloudwatchLogGroupName:
    Type: String
    Description: "Name of triggering log group"
    #Default: <<LOGGROUP_NAME>>

  # NOTE: A filterPattern is optional
  #EventCloudwatchLogGroupFilterPattern:
  #  Type: String
  #  Default: <<FILTER_PATTERN>>
{%- elif cookiecutter.event_source == "dynamodb" %}
  EventDynamoDBStreamArn:
    Type: String
    Description: "ARN of stream"
    #Default: <<required: STREAM_ARN>>

  EventDynamoDBStreamStartingPosition:
    Type: String
    Description: "Stream starting position for function"
    AllowedValues:
      - 'LATEST'
      - 'TRIM_HORIZON'
    Default: 'LATEST'

  EventDynamoDBStreamBatchSize:
    Type: String
    Description: "Size of event batch"
    Default: 100

  # FIXME: Need a Condition block for this.
  EventDynamoDBStreamEnabled:
    Type: String
    Description: "If processing is enabled"
    AllowedValues:
      - True
      - False
    Default: True

{%- elif cookiecutter.event_source == "kinesis" %}
  EventKinesisStreamArn:
    Type: String
    Description: "ARN of stream"
    #Default: <<required: STREAM_ARN>>

  EventKinesisStreamStartingPosition:
    Type: String
    Description: "Stream starting position for function"
    AllowedValues:
      - 'LATEST'
      - 'TRIM_HORIZON'
    Default: 'LATEST'

  EventKinesisStreamBatchSize:
    Type: String
    Description: "Size of event batch"
    Default: 100

  # FIXME: Need a Condition block for this.
  EventKinesisStreamEnabled:
    Type: String
    Description: "If processing is enabled"
    AllowedValues:
      - True
      - False
    Default: True

{%- elif cookiecutter.event_source == "s3" %}
  EventS3Bucket:
    Type: String
    Description: "S3 bucket name"
    #Default: <<required: BUCKET_NAME>>

  EventS3EventsList:
    Type: List
    Description: "List of events to trigger on"
    AllowedValues:
      - s3:ObjectCreated:*
      - s3:ObjectCreated:Put
      - s3:ObjectCreated:Post
      - s3:ObjectCreated:Copy
      - s3:ObjectCreated:CompleteMultipartUpload
      - s3:ObjectRemoved:*
      - s3:ObjectRemoved:Delete
      - s3:ObjectRemoved:DeleteMarkerCreated
      - s3:ObjectRestore:Post
      - s3:ObjectRestore:Completed
      - s3:ReducedRedundancyLostObject
    #Default:
    #  - <<required: EVENT>>

  #EventS3FilterRuleList:
  #  Type: List
  #  Description: "List of event filter rules."
  #  Default:
  #    - <<FILTER_RULE>>
{%- elif cookiecutter.event_source == "schedule" %}
  EventSchedule:
    Type: String
    Description: "event schedule"
    #Default: <<required: SCHEDULE>>
{%- elif cookiecutter.event_source == "sns" %}
  EventSnsTopicArn:
    Type: String
    Description: "SNS Topic Arn"
    #Default: <<required: SNS_TOPIC_ARN>>

{%- elif cookiecutter.event_source == "sqs" %}
  EventSqsQueueArn:
    Type: String
    Description: "ARN of stream"
    #Default: <<required: QUEUE_ARN>>

  EventSqsQueueBatchSize:
    Type: String
    Description: "Size of event batch"
    Default: 10

  # FIXME: Need a Condition block for this.
  EventSqsQueueEnabled:
    Type: String
    Description: "If processing is enabled"
    AllowedValues:
      - True
      - False
    Default: True
{%- endif %}
{%- endif %}

{% if cookiecutter.event_destination != "other" %}
{%- if cookiecutter.event_destination == "kinesis" %}
  KinesisStreamRetentionHours:
    Type: Number
    Description: "Kinesis stream retention period in hours"
    Default: 24

  KinesisStreamShardCount:
    Type: Number
    Description: "Kinesis stream shard count"
    #Default: <<required: SHARD_COUNT>>

{%- elif cookiecutter.event_destination == "s3" %}
  S3BucketAccessControl:
    Type: String
    Description: 'S3 bucket access control'
    AllowedValues:
      - 'Private'
      - 'PublicRead'
      - 'PublicReadWrite'
      - 'AwsExecRead'
      - 'AuthenticatedRead'
      - 'BucketOwnerRead'
      - 'BucketOwnerFullControl'
      - 'LogDeliveryWrite'
    Default: 'Private'

  S3BucketVersioningStatus:
    Type: String
    Description: 'Bucket versioning status'
    Default: 'Suspended'

{%- elif cookiecutter.event_destination == "sqs" %}
  SqsQueueDelaySeconds:
    Type: Number
    Description: "Sqs queue delayed delivery in seconds"
    Default: 0

  # FIXME: Not sure why this is failing
  #SqsQueueFifoQueue:
  #  Type: String
  #  Description: "SQS queue FIFO queue"
  #  AllowedValues:
  #    - True
  #    - False
  #  Default: False

  SqsQueueMessageRetentionPeriod:
    Type: Number
    Description: "SQS queue message retention period"
    Default: 345600

  SqsQueueReceiveMessageWaitTimeSeconds:
    Type: Number
    Description: "SQS queue polling length in seconds"
    Default: 0

  SqsQueueVisibilityTimeout:
    Type: Number
    Description: "SQS queue visibility timeout in seconds"
    Default: 30

{%- endif -%}
{%- endif %}

Mappings:
  XRaySDKEnabled:
    Enabled:
      Enabled: "true"
    Disabled:
      Enabled: "false"

Globals:
  Function:
    Environment:
      Variables:
        LOG_LEVEL:
          Ref: LogLevel
        AWS_XRAY_SDK_ENABLED:
          Fn::FindInMap:
            - XRaySDKEnabled
            - Ref: XRaySDKEnabled
            - Enabled
    Tags:
      ServiceName: !Ref ServiceName
      ServiceEnv: !Ref ServiceEnv
    Tracing: !Ref XRayTracingMode


Resources:
{% if cookiecutter.event_source == "apigateway" %}
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: ServiceEnv
      #DefinitionUri: swagger.yml
{%- endif %}


{% if cookiecutter.event_destination != "other" %}
{%- if cookiecutter.event_destination == "dynamodb" %}
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    # NOTE: Retain data by default
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        #- AttributeName: "sk"
        #  AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        #- AttributeName: "sk"
        #  KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"

{%- elif cookiecutter.event_destination == "kinesis" %}
  KinesisStream:
    Type: AWS::Kinesis::Stream
    RetentionPeriodHours:
      Ref: KinesisStreamRetentionHours
    ShardCount:
      Ref: KinesisStreamShardCount

{%- elif cookiecutter.event_destination == "s3" %}
  S3Bucket:
    Type: AWS::S3::Bucket
    # NOTE: Retain data by default
    DeletionPolicy: 'Retain'
    Properties:
      AccessControl:
        Ref: S3BucketAccessControl
      VersioningConfiguration:
        Status:
          Ref: S3BucketVersioningStatus

{%- elif cookiecutter.event_destination == "sns" %}
  SnsTopic:
    Type: AWS::SNS::Topic

{%- elif cookiecutter.event_destination == "sqs" %}
  SqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds:
        Ref: SqsQueueDelaySeconds
      # FIXME: Not working
      #FifoQueue:
      #  Ref: SqsQueueFifoQueue
      MessageRetentionPeriod:
        Ref: SqsQueueMessageRetentionPeriod
      ReceiveMessageWaitTimeSeconds:
        Ref: SqsQueueReceiveMessageWaitTimeSeconds
      VisibilityTimeout:
        Ref: SqsQueueVisibilityTimeout
{%- endif %}
{%- endif %}

{% if cookiecutter.enable_cloudwatch_topic == "yes" %}
  CloudWatchTopic:
    Type: AWS::SNS::Topic
{%- endif %}


Outputs:
{%- if cookiecutter.event_source == "apigateway" %}
  RestApiRoot:
    Description: "API Gateway endpoint URL for function"
    Value:
      Fn::Sub: "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServiceEnv}"
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-RestApiRoot"
{%- endif %}

{% if cookiecutter.event_destination != "other" %}
{%- if cookiecutter.event_destination == "dynamodb" %}
  DynamoDBTableArn:
    Description: "ARN of DynamoDB table"
    Value:
      Fn::GetAtt: DynamoDBTable.Arn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-DynamoDBTableArn"

  DynamoDBTableName:
    Description: "Name of DynamoDB table"
    Value:
      Ref: DynamoDBTable
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-DynamoDBTableName"

{%- elif cookiecutter.event_destination == "kinesis" %}
  KinesisStreamArn:
    Description: "ARN of Kinesis stream"
    Value:
      Fn::GetAtt: KinesisStream.Arn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-KinesisStreamArn"

  KinesisStreamName:
    Description: "Name of Kinesis stream"
    Value:
      Ref: KinesisStream
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-KinesisStreamName"

{%- elif cookiecutter.event_destination == "s3" %}
  S3BucketArn:
    Description: "ARN of S3 bucket"
    Value:
      Fn::GetAtt: S3Bucket.Arn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-S3BucketArn"

  S3BucketDomainName:
    Description: "Domain name of S3 bucket"
    Value:
      Fn::GetAtt: S3Bucket.DomainName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-S3BucketDomainName"

  S3BucketName:
    Description: "Name of S3 bucket"
    Value:
      Ref: S3Bucket
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-S3BucketName"

{%- elif cookiecutter.event_destination == "sns" %}
  SnsTopicArn:
    Description: "ARN of SNS topic"
    Value:
      Ref: SnsTopic
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-SnsTopicArn"

  SnsTopiceName:
    Description: "Name of SNS topic"
    Value:
      Fn::GetAtt: SnsTopic.TopicName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-SnsTopiceName"

{%- elif cookiecutter.event_destination == "sqs" %}
  SqsQueueArn:
    Description: "ARN of SQS queue"
    Value:
      Fn::GetAtt: SqsQueue.Arn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-SqsQueueArn"

  SqsQueueName:
    Description: "Name of SQS queue"
    Value:
      Fn::GetAtt: SqsQueue.QueueName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-SqsQueueName"

  SqsQueueUrl:
    Description: "Url of SQS queue"
    Value:
      Ref: SqsQueue
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-SqsQueueUrl"

{%- endif %}
{%- endif %}

{% if cookiecutter.enable_cloudwatch_topic == "yes" %}
  CloudWatchTopicArn:
    Description: "ARN of CloudWatch topic"
    Value:
      Ref: CloudWatchTopic
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-CloudWatchTopicArn"
{%- endif %}

